Redmine#8674: Added label to trovy job

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -21,8 +21,12 @@ else
 fi
 # Capture the exit code of ESLint
 ESLINT_STATUS=$?
+#Running Trivy to check for vulnerabilities
+trivy fs .
+# Capture the exit code of TRIVY
+TRIVY_STATUS=$?
 # Exit with code according to PHPCS and ESLint
-if [ $PHPCS_STATUS -ne 0 ] || [ $ESLINT_STATUS -ne 0 ]; then
+if [ $PHPCS_STATUS -ne 0 ] || [ $ESLINT_STATUS -ne 0 ] || [ $TRIVY_STATUS -ne 0 ]; then
   exit 1
 else
   exit 0
